# fastapi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dna-visualizer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dna-visualizer
  template:
    metadata:
      labels:
        app: dna-visualizer
    spec:
      containers:
      - name: dna-visualizer
        image: ampersandor/dna-visualizer
        resources:
                requests:
                        cpu: "250m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dna-visualizer-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: dna-visualizer

